package com.example.vladimir.financetracker

object Routes{
    const val DESTINATION_FRAGMENT = "DESTINATION_FRAGMENT"
    const val TRANSACTION_FRAGMENT = "TRANSACTION_FRAGMENT"
    const val SETTINGS_FRAGMENT = "SETTINGS_FRAGMENT"
    const val ABOUT_FRAGMENT = "ABOUT_FRAGMENT"
    const val WALLET_FRAGMENT = "WALLET_FRAGMENT"
    const val STATISTICS_FRAGMENT = "STATISTICS_FRAGMENT"
}