package com.example.vladimir.financetracker

object Routes{
    const val DESTINATION_FRAGMENT = "DESTINATION_FRAGMENT"
    const val TRANSACTION_FRAGMENT = "TRANSACTION_FRAGMENT"
    const val SETTINGS_FRAGMENT = "SETTINGS_FRAGMENT"
    const val ABOUT_FRAGMENT = "ABOUT_FRAGMENT"
    const val WALLETS_FRAGMENT = "WALLETS_FRAGMENT"
    const val STATISTICS_FRAGMENT = "STATISTICS_FRAGMENT"
    const val MAIN_FRAGMENT = "MAIN_FRAGMENT"
    const val ADD_WALLET_FRAGMENT = "ADD_WALLET_FRAGMENT"
}